version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: helpdesk-postgres
    environment:
      POSTGRES_DB: helpdesk_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
