---
name: "Deploy to Production (SSH Debug)"

on:
  push:
    branches: [main]

jobs:
  debug-connection:
    name: Debug SSH Connection
    runs-on: ubuntu-latest
    
    steps:
      - name: Test SSH Connection
        env:
          VM_IP: ${{ secrets.VM_IP }}
        run: |
          echo "🔍 Debugging SSH connection to server..."
          echo "Target IP: $VM_IP"
          
          # Test if port 22 is reachable
          echo "Testing port 22 connectivity..."
          timeout 10 bash -c "echo >/dev/tcp/$VM_IP/22" && echo "✅ Port 22 reachable" || echo "❌ Port 22 not reachable"
          
          # Test SSH with verbose output
          echo "Testing SSH connection with verbose output..."
          ssh -v -o StrictHostKeyChecking=no -o ConnectTimeout=10 ubuntu@$VM_IP 'echo "SSH works!"' || echo "❌ SSH failed"
          
          echo ""
          echo "🔧 If connection failed, check:"
          echo "1. Is the VM_IP secret correct? Current value: $VM_IP"
          echo "2. Is your server running?"
          echo "3. Is SSH service enabled on the server?"
          echo "4. Is the SSH_PRIVATE_KEY secret valid?"
          echo "5. Are firewall rules allowing SSH on port 22?"
