---
name: "Deploy to Production (SSH Debug)"

on:
  workflow_dispatch: # Only manual trigger, not on push

jobs:
  debug-connection:
    name: Debug SSH Connection
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH Connection
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
        run: |
          echo "🚀 Deploying to production server..."
          echo "🔍 Testing server connectivity..."
          echo "Server IP: $VM_HOST"

          # Test if port 22 is reachable
          timeout 10 bash -c "echo >/dev/tcp/$VM_HOST/22" && echo "✅ Port 22 is reachable" || echo "❌ Port 22 not reachable"

          # Test SSH with verbose output
          echo "🔐 Testing SSH connection..."
          ssh -v -o StrictHostKeyChecking=no -o ConnectTimeout=30 $VM_USER@$VM_HOST 'echo "SSH connection successful!"' || {
            echo "❌ SSH connection failed. Checking common issues..."
            echo "- Verify VM_HOST secret is correct: $VM_HOST"
            echo "- Verify SSH_PRIVATE_KEY secret contains valid private key"
            echo "- Check if server is running and SSH service is enabled"
            echo "- Verify firewall allows SSH on port 22"
            exit 1
          }

          echo "✅ SSH connection successful!"
