name: 🚀 Production Deployment (Docker Ready)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "production"
        type: choice
        options:
          - production
          - staging

env:
  DEPLOY_DIR: /home/${{ secrets.VM_USER }}/helpdesk-deployment

jobs:
  deploy:
    name: 🚀 Deploy Helpdesk System
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🔑 Add VM to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: ✅ Verify Docker Access
        run: |
          echo "✅ Verifying Docker access..."
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            echo 'Current user: \$(whoami)'
            echo 'Current groups: \$(groups)'
            echo 'Testing Docker access:'
            docker --version
            docker ps
            echo '✅ Docker access confirmed!'
          "

      - name: 🧹 Clean Previous Deployment
        run: |
          echo "🧹 Cleaning previous deployment..."
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            # Stop existing containers
            if [ -f $DEPLOY_DIR/docker-compose.prod.yml ]; then
              cd $DEPLOY_DIR
              docker-compose -f docker-compose.prod.yml down --remove-orphans || echo 'No containers to stop'
            fi
            
            # Clean up old deployment
            rm -rf $DEPLOY_DIR || echo 'No previous deployment to clean'
            
            # Clean Docker system
            docker system prune -f
            
            echo '✅ Cleanup completed'
          "

      - name: 📂 Create Deployment Directory
        run: |
          echo "📂 Creating deployment directory..."
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            mkdir -p $DEPLOY_DIR
            cd $DEPLOY_DIR
            echo 'Deployment directory: \$(pwd)'
          "

      - name: 📤 Upload Application Files
        run: |
          echo "📤 Uploading application files..."
          
          # Create deployment archive
          tar -czf helpdesk-deploy.tar.gz \
            backend/ \
            frontend/ \
            docker-compose.prod.yml \
            .env.production \
            deploy-production.sh \
            package*.json || true
          
          # Upload to VM
          scp helpdesk-deploy.tar.gz ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:$DEPLOY_DIR/
          
          # Extract on VM
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            cd $DEPLOY_DIR
            tar -xzf helpdesk-deploy.tar.gz
            rm helpdesk-deploy.tar.gz
            echo '✅ Files uploaded and extracted'
            ls -la
          "

      - name: 🔧 Set Permissions
        run: |
          echo "🔧 Setting file permissions..."
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            cd $DEPLOY_DIR
            chmod +x *.sh 2>/dev/null || echo 'No shell scripts to make executable'
            echo '✅ Permissions set'
          "

      - name: 🐳 Build Docker Images
        run: |
          echo "🐳 Building Docker images..."
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            cd $DEPLOY_DIR
            
            echo 'Building backend image...'
            docker build -t helpdesk-backend:latest ./backend/
            
            echo 'Building frontend image...'
            docker build -t helpdesk-frontend:latest ./frontend/
            
            echo '✅ Docker images built successfully'
            docker images | grep helpdesk
          "

      - name: 🚀 Deploy Application
        run: |
          echo "🚀 Starting application containers..."
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            cd $DEPLOY_DIR
            
            echo 'Starting containers...'
            docker-compose -f docker-compose.prod.yml up -d
            
            echo 'Waiting for containers to initialize...'
            sleep 20
            
            echo '✅ Containers started'
          "

      - name: 🔍 Verify Deployment
        run: |
          echo "🔍 Verifying deployment..."
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            cd $DEPLOY_DIR
            
            echo 'Container status:'
            docker-compose -f docker-compose.prod.yml ps
            
            echo 'Container health:'
            docker-compose -f docker-compose.prod.yml logs --tail=10 backend
            docker-compose -f docker-compose.prod.yml logs --tail=10 frontend
            docker-compose -f docker-compose.prod.yml logs --tail=10 db
          "

      - name: 🌐 Test Endpoints
        run: |
          echo "🌐 Testing application endpoints..."
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            echo 'Testing internal endpoints...'
            
            # Wait a bit more for full startup
            sleep 10
            
            # Test backend health
            if curl -f http://localhost:3001/health -s; then
              echo '✅ Backend API responding'
            else
              echo '⚠️ Backend API not responding yet'
            fi
            
            # Test frontend
            if curl -f http://localhost:80 -s -o /dev/null; then
              echo '✅ Frontend responding'
            else
              echo '⚠️ Frontend not responding yet'
            fi
            
            # Test database
            if docker-compose -f $DEPLOY_DIR/docker-compose.prod.yml exec -T db pg_isready -U helpdesk_user; then
              echo '✅ Database ready'
            else
              echo '⚠️ Database not ready yet'
            fi
          "

      - name: 📋 Deployment Summary
        run: |
          echo ""
          echo "🎉 DEPLOYMENT COMPLETED SUCCESSFULLY!"
          echo "====================================="
          echo ""
          echo "🔗 **Application URLs:**"
          echo "• Frontend: http://${{ secrets.VM_HOST }}"
          echo "• Backend API: http://${{ secrets.VM_HOST }}:3001"
          echo "• Health Check: http://${{ secrets.VM_HOST }}:3001/health"
          echo "• WebSocket: ws://${{ secrets.VM_HOST }}:3001"
          echo ""
          echo "👤 **Default Admin Account:**"
          echo "• Email: admin@example.com"
          echo "• Password: admin123"
          echo ""
          echo "👤 **Default User Account:**"
          echo "• Email: user@example.com"
          echo "• Password: user123"
          echo ""
          echo "⚠️ **IMPORTANT: Configure GCP Firewall Rules**"
          echo "Before accessing the application, configure firewall rules for:"
          echo "• Port 80 (Frontend)"
          echo "• Port 3001 (Backend API)"
          echo ""
          echo "📋 **Next Steps:**"
          echo "1. Configure GCP firewall rules"
          echo "2. Access application at http://${{ secrets.VM_HOST }}"
          echo "3. Test user authentication and ticket creation"
          echo "4. Verify real-time WebSocket updates"
          echo ""
          echo "🔧 **Troubleshooting Commands:**"
          echo "• Check containers: docker-compose -f $DEPLOY_DIR/docker-compose.prod.yml ps"
          echo "• View logs: docker-compose -f $DEPLOY_DIR/docker-compose.prod.yml logs"
          echo "• Restart services: docker-compose -f $DEPLOY_DIR/docker-compose.prod.yml restart"
