name: Fast Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Kill any running containers
          docker kill $(docker ps -q) || true
          docker rm $(docker ps -aq) || true
          
          # Go to app directory
          cd /home/kovendhan2535/helpdesk-app || mkdir -p /home/kovendhan2535/helpdesk-app && cd /home/kovendhan2535/helpdesk-app
          
          # Get latest code
          git clone --depth 1 https://github.com/kovendhan5/Helpdesk-Ticketing-System.git . || git pull origin main
          
          # Quick deploy
          docker-compose -f docker-compose.simple.yml up -d --build --force-recreate
          
          echo "Deployment complete!"
          docker ps
