name: 🧪 Test GitHub Secrets

on:
  workflow_dispatch: # Manual trigger only

jobs:
  test-secrets:
    name: Test GitHub Secrets Configuration
    runs-on: ubuntu-latest

    steps:
      - name: 🔍 Check Secrets
        run: |
          echo "=== GitHub Secrets Test ==="

          # Check if secrets exist (without exposing values)
          if [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "✅ SSH_PRIVATE_KEY: CONFIGURED (${#PRIVATE_KEY} characters)"
          else
            echo "❌ SSH_PRIVATE_KEY: NOT CONFIGURED"
          fi

          if [ -n "${{ secrets.VM_HOST }}" ]; then
            echo "✅ VM_HOST: CONFIGURED"
          else
            echo "❌ VM_HOST: NOT CONFIGURED"
          fi

          if [ -n "${{ secrets.VM_USER }}" ]; then
            echo "✅ VM_USER: CONFIGURED"
          else
            echo "❌ VM_USER: NOT CONFIGURED"
          fi
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🔑 Test SSH Key Format
        if: ${{ secrets.SSH_PRIVATE_KEY != '' }}
        run: |
          echo "Testing SSH key format..."

          # Check if key starts correctly
          if echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -1 | grep -q "BEGIN.*PRIVATE KEY"; then
            echo "✅ SSH key starts with correct header"
          else
            echo "❌ SSH key format error - missing header"
          fi

          # Check if key ends correctly  
          if echo "${{ secrets.SSH_PRIVATE_KEY }}" | tail -1 | grep -q "END.*PRIVATE KEY"; then
            echo "✅ SSH key ends with correct footer"
          else
            echo "❌ SSH key format error - missing footer"
          fi

      - name: 🌐 Test VM Connectivity
        if: ${{ secrets.VM_HOST != '' }}
        run: |
          echo "Testing VM connectivity..."

          # Test if hostname resolves
          if nslookup ${{ secrets.VM_HOST }}; then
            echo "✅ VM hostname resolves"
          else
            echo "❌ VM hostname does not resolve"
          fi

          # Test if port 22 is open
          if timeout 10 bash -c "</dev/tcp/${{ secrets.VM_HOST }}/22"; then
            echo "✅ SSH port 22 is accessible"
          else
            echo "❌ SSH port 22 is not accessible"
          fi
