name: 🔍 Validate GitHub Secrets

on:
  workflow_dispatch: # Manual trigger only

jobs:
  validate-secrets:
    runs-on: ubuntu-latest
    name: 🔍 Check Required Secrets
    steps:
      - name: Validate All Required Secrets
        run: |
          echo "🔍 Validating GitHub Secrets for GCP Deployment..."
          echo "=================================================="
          
          # Check SSH_PRIVATE_KEY
          if [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "✅ SSH_PRIVATE_KEY: Configured"
            # Check if it looks like a valid SSH key
            if echo "${{ secrets.SSH_PRIVATE_KEY }}" | grep -q "BEGIN.*PRIVATE KEY"; then
              echo "   └── ✅ Appears to be a valid SSH private key"
            else
              echo "   └── ⚠️  May not be a valid SSH private key format"
            fi
          else
            echo "❌ SSH_PRIVATE_KEY: MISSING"
            echo "   └── Add your SSH private key to GitHub Secrets"
          fi
          
          # Check DB_PASSWORD
          if [ -n "${{ secrets.DB_PASSWORD }}" ]; then
            echo "✅ DB_PASSWORD: Configured"
            echo "   └── Length: $(echo '${{ secrets.DB_PASSWORD }}' | wc -c) characters"
          else
            echo "❌ DB_PASSWORD: MISSING"
            echo "   └── Add database password to GitHub Secrets"
          fi
          
          # Check JWT_SECRET
          if [ -n "${{ secrets.JWT_SECRET }}" ]; then
            echo "✅ JWT_SECRET: Configured"
            echo "   └── Length: $(echo '${{ secrets.JWT_SECRET }}' | wc -c) characters"
          else
            echo "❌ JWT_SECRET: MISSING"
            echo "   └── Add JWT secret to GitHub Secrets"
          fi
          
          # Check REDIS_PASSWORD
          if [ -n "${{ secrets.REDIS_PASSWORD }}" ]; then
            echo "✅ REDIS_PASSWORD: Configured"
            echo "   └── Length: $(echo '${{ secrets.REDIS_PASSWORD }}' | wc -c) characters"
          else
            echo "❌ REDIS_PASSWORD: MISSING"
            echo "   └── Add Redis password to GitHub Secrets"
          fi
          
          echo ""
          echo "=================================================="
          
          # Check if all secrets are present
          if [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ] && \
             [ -n "${{ secrets.DB_PASSWORD }}" ] && \
             [ -n "${{ secrets.JWT_SECRET }}" ] && \
             [ -n "${{ secrets.REDIS_PASSWORD }}" ]; then
            echo "🎉 ALL SECRETS CONFIGURED!"
            echo "✅ Ready for GCP deployment"
            echo ""
            echo "Next steps:"
            echo "1. Run the 'Deploy Helpdesk to GCP Production' workflow"
            echo "2. Monitor deployment progress"
            echo "3. Access your app at http://34.173.186.108:8080"
          else
            echo "❌ MISSING SECRETS DETECTED"
            echo "🔧 Please add the missing secrets before deploying"
            echo ""
            echo "Quick setup:"
            echo "1. Go to: Repository Settings → Secrets and variables → Actions"
            echo "2. Click 'New repository secret'"
            echo "3. Add each missing secret with the correct name and value"
            echo ""
            echo "Values from your .env file:"
            echo "DB_PASSWORD=mU68QoL8YGh/DTWOHBgFHyF2HliCYH5d"
            echo "JWT_SECRET=NKg9g6243cWlnXHbPBT4TC5eBxghgAYIgRl0bTx1I6rkC/f1aetZdx+PEvLCp82p"
            echo "REDIS_PASSWORD=94ABRM4sG6fppWiIUQRckDIY"
            exit 1
          fi
